import assert from 'node:assert/strict';import fs from 'node:fs';
const base='http://localhost:5173';let cookie='';const credentials=JSON.parse(fs.readFileSync('work/test-auth.json','utf8'));
async function request(path,value,auth=true){const r=await fetch(base+path,{method:value?'POST':'GET',headers:{...(value?{'Content-Type':'application/json'}:{}),...(auth&&cookie?{Cookie:cookie}:{})},body:value?JSON.stringify(value):undefined});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}return {status:r.status,data,headers:r.headers};}
const setup=await request('/api/auth/setup',credentials);assert.ok(setup.status===200||String(setup.data.error).includes('already exists'),JSON.stringify(setup.data));
const login=await request('/api/auth/login',credentials);assert.equal(login.status,200,JSON.stringify(login.data));cookie=login.headers.get('set-cookie').split(';')[0];fs.writeFileSync('work/test-cookie.txt',cookie);
assert.equal((await request('/api/admin/data',null,false)).status,401);
const room={id:'qa-room',name:'QA Test Room (not property inventory)',description:'Test-only inventory for automated validation.',capacity:2,beds:'Test configuration',bathroom:'Test bathroom',price:1000,image:'/images/room.avif',published:true};
assert.equal((await request('/api/admin/save',{collection:'rooms',entry:room})).status,200);
await request('/api/admin/save',{collection:'website_settings',entry:{id:'direct_booking_enabled',value:true}});
const dates={checkin:'2027-05-10',checkout:'2027-05-12',guests:2};let availability=await request('/api/availability?'+new URLSearchParams(dates));assert.ok(availability.data.rooms.some(r=>r.id==='qa-room'));
const guest={...dates,first_name:'Test',last_name:'Guest',email:'guest@example.test',phone:'0000000000',adults:2,children:0,room_id:'qa-room'};
const attempts=await Promise.all([request('/api/bookings',{...guest,idempotency_key:crypto.randomUUID()},false),request('/api/bookings',{...guest,idempotency_key:crypto.randomUUID()},false)]);assert.equal(attempts.filter(r=>r.status===200).length,1,'Exactly one concurrent booking must succeed');assert.equal(attempts.filter(r=>r.status!==200).length,1);
availability=await request('/api/availability?'+new URLSearchParams(dates));assert.ok(!availability.data.rooms.some(r=>r.id==='qa-room'));
assert.equal((await request('/api/admin/block',{entry:{id:'qa-conflict',room_id:'qa-room',checkin:dates.checkin,checkout:dates.checkout,notes:'Must conflict'}})).status,409);
let data=(await request('/api/admin/data')).data.data;const booking=data.bookings.find(b=>b.room_id==='qa-room');assert.ok(booking);assert.equal((await request('/api/admin/booking',{entry:{...booking,status:'CANCELLED',notes:'QA cleanup'}})).status,200);
assert.equal((await request('/api/admin/save',{collection:'functions',entry:{id:'qa-function',name:'QA Function',checkin:dates.checkin,checkout:dates.checkout,status:'CONFIRMED',affected_room_ids:['qa-room']}})).status,200);
availability=await request('/api/availability?'+new URLSearchParams(dates));assert.ok(!availability.data.rooms.some(r=>r.id==='qa-room'),'Function must block room');
assert.equal((await request('/api/admin/save',{collection:'functions',entry:{id:'qa-function',name:'QA Function',checkin:dates.checkin,checkout:dates.checkout,status:'DECLINED',affected_room_ids:['qa-room']}})).status,200);
const integration={id:'qa-integration',name:'Test calendar',channel:'OTHER',room_id:'qa-room',enabled:false};await request('/api/admin/save',{collection:'integration_settings',entry:integration});
const ics='BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:test-event\r\nDTSTART;VALUE=DATE:20270510\r\nDTEND;VALUE=DATE:20270512\r\nEND:VEVENT\r\nEND:VCALENDAR';
assert.equal((await request('/api/admin/sync',{id:integration.id,ics})).status,200);
availability=await request('/api/availability?'+new URLSearchParams(dates));assert.ok(!availability.data.rooms.some(r=>r.id==='qa-room'),'ICS import must block room');
assert.equal((await request('/api/admin/sync',{id:integration.id,ics:'invalid feed'})).status,400);data=(await request('/api/admin/data')).data.data;assert.ok(data.availability_blocks.some(b=>b.integration_id===integration.id),'Invalid feed retains previous blocks');
const contact=await request('/api/contact',{name:'QA Enquiry',email:'qa@example.test',phone:'0000000000',subject:'Test enquiry',message:'Automated local test of persistent contact enquiries.',website:''},false);assert.equal(contact.status,200);
assert.equal((await request('/api/contact',{name:'Bot',email:'qa@example.test',subject:'Spam',message:'Automated spam example.',website:'https://spam.invalid'},false)).status,400);
assert.equal((await request('/api/functions',{name:'QA Event',email:'qa@example.test',phone:'0000000000',subject:'QA event',message:'Test event enquiry for persistence.',preferred_date:'2027-06-01',guests:20,event_type:'Family gathering',start_time:'12:00',end_time:'16:00',catering:'Discuss meals',accommodation:'Yes'},false)).status,200);
await request('/api/admin/save',{collection:'rooms',entry:{...room,published:false}});await request('/api/admin/save',{collection:'website_settings',entry:{id:'direct_booking_enabled',value:false}});
for(const p of ['/','/accommodation','/functions','/contact','/gallery','/journal','/journal/where-to-stay-near-louis-trichardt','/eat-drink','/book','/admin/calendar','/sitemap.xml','/robots.txt'])assert.equal((await request(p)).status,200,p);
console.log('PASS: authentication, protected API, room CMS, availability, concurrent booking exclusion, booking cancellation, function conflicts, ICS import + fail-safe retention, contact + function persistence, honeypot, and route checks.');
