CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE FUNCTION iso_date(v text) RETURNS date LANGUAGE sql IMMUTABLE STRICT AS 'SELECT make_date(substring(v,1,4)::int,substring(v,6,2)::int,substring(v,9,2)::int)';
CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE,data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE rooms (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE guests (id TEXT PRIMARY KEY, email TEXT,data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE integration_settings (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE room_images (id TEXT PRIMARY KEY, room_id TEXT REFERENCES rooms(id) ON DELETE CASCADE,data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE amenities (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE bookings (id TEXT PRIMARY KEY, room_id TEXT NOT NULL REFERENCES rooms(id), guest_id TEXT NOT NULL REFERENCES guests(id), checkin TEXT NOT NULL, checkout TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('ENQUIRY','PENDING','CONFIRMED','PAID','CHECKED-IN','CHECKED-OUT','CANCELLED','NO-SHOW')), source TEXT NOT NULL CHECK(source IN ('DIRECT','LEKKESLAAP','BOOKING.COM','ADMIN','OTHER')), idempotency_key TEXT UNIQUE, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, CHECK (checkout > checkin));
CREATE TABLE booking_guests (id TEXT PRIMARY KEY, booking_id TEXT REFERENCES bookings(id), guest_id TEXT REFERENCES guests(id),data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE booking_sources (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE availability_blocks (id TEXT PRIMARY KEY, room_id TEXT NOT NULL REFERENCES rooms(id), checkin TEXT NOT NULL, checkout TEXT NOT NULL, source TEXT NOT NULL, external_uid TEXT, integration_id TEXT REFERENCES integration_settings(id), data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, CHECK(checkout>checkin));
CREATE TABLE functions (id TEXT PRIMARY KEY, checkin TEXT, checkout TEXT, status TEXT,data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE function_enquiries (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE blog_posts (id TEXT PRIMARY KEY, slug TEXT UNIQUE,data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE blog_categories (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE gallery_images (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE testimonials (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE faqs (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE website_settings (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE seo_metadata (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE sessions (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), token_hash TEXT UNIQUE, expires_at TEXT,data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE reset_tokens (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), token_hash TEXT UNIQUE, expires_at TEXT,data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE rate_limits (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE email_outbox (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE contact_enquiries (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE menu_items (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX bookings_dates ON bookings(room_id,checkin,checkout,status);
CREATE INDEX blocks_dates ON availability_blocks(room_id,checkin,checkout);
CREATE INDEX guest_email ON guests(email);

ALTER TABLE bookings ADD CONSTRAINT booking_no_overlap EXCLUDE USING gist (room_id WITH =, daterange(iso_date(checkin),iso_date(checkout),'[)') WITH &&) WHERE (status IN ('PENDING','CONFIRMED','PAID','CHECKED-IN'));
CREATE OR REPLACE FUNCTION guard_inventory() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 PERFORM pg_advisory_xact_lock(hashtextextended(NEW.room_id,0));
 IF TG_TABLE_NAME='bookings' THEN
 IF NEW.status NOT IN ('PENDING','CONFIRMED','PAID','CHECKED-IN') THEN RETURN NEW; END IF;
 IF EXISTS(SELECT 1 FROM availability_blocks WHERE room_id=NEW.room_id AND checkin<NEW.checkout AND checkout>NEW.checkin) THEN RAISE EXCEPTION 'blocked date conflict'; END IF;
 ELSIF TG_TABLE_NAME='availability_blocks' THEN
 IF EXISTS(SELECT 1 FROM bookings WHERE room_id=NEW.room_id AND status IN ('PENDING','CONFIRMED','PAID','CHECKED-IN') AND checkin<NEW.checkout AND checkout>NEW.checkin) THEN RAISE EXCEPTION 'booking conflict'; END IF;
 END IF; RETURN NEW; END $$;
CREATE TRIGGER bookings_guard BEFORE INSERT OR UPDATE ON bookings FOR EACH ROW EXECUTE FUNCTION guard_inventory();
CREATE TRIGGER blocks_guard BEFORE INSERT OR UPDATE ON availability_blocks FOR EACH ROW EXECUTE FUNCTION guard_inventory();
CREATE OR REPLACE FUNCTION create_reservation(reservation jsonb,guest_record jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$ DECLARE t text:=now()::text; BEGIN
 INSERT INTO guests(id,email,data,created_at,updated_at) VALUES(guest_record->>'id',guest_record->>'email',guest_record,t,t) ON CONFLICT(id) DO NOTHING;
 INSERT INTO bookings(id,room_id,guest_id,checkin,checkout,status,source,idempotency_key,data,created_at,updated_at) VALUES(reservation->>'id',reservation->>'room_id',guest_record->>'id',reservation->>'checkin',reservation->>'checkout',reservation->>'status',reservation->>'source',reservation->>'idempotency_key',reservation,t,t);
 INSERT INTO booking_guests(id,booking_id,guest_id,data,created_at,updated_at) VALUES(gen_random_uuid()::text,reservation->>'id',guest_record->>'id','{}',t,t);
 INSERT INTO audit_logs(id,data,created_at,updated_at) VALUES(gen_random_uuid()::text,jsonb_build_object('action','booking.created','booking_id',reservation->>'id'),t,t);
 RETURN reservation; END $$;
CREATE OR REPLACE FUNCTION take_rate_limit(key_id text,max_count int) RETURNS boolean LANGUAGE plpgsql AS $$ DECLARE count_value int; BEGIN
 INSERT INTO rate_limits(id,data,created_at,updated_at) VALUES(key_id,'{"count":1}',now()::text,now()::text) ON CONFLICT(id) DO UPDATE SET data=jsonb_build_object('count',(rate_limits.data->>'count')::int+1) RETURNING (data->>'count')::int INTO count_value;
 RETURN count_value<=max_count; END $$;
CREATE OR REPLACE FUNCTION replace_channel_blocks(integration text,blocks jsonb) RETURNS void LANGUAGE plpgsql AS $$ DECLARE b jsonb; BEGIN
 DELETE FROM availability_blocks WHERE integration_id=integration;
 FOR b IN SELECT * FROM jsonb_array_elements(blocks) LOOP
 INSERT INTO availability_blocks(id,room_id,checkin,checkout,source,external_uid,integration_id,data,created_at,updated_at) VALUES(b->>'id',b->>'room_id',b->>'checkin',b->>'checkout',b->>'source',b->>'external_uid',integration,b,now()::text,now()::text);
 END LOOP; END $$;
REVOKE ALL ON FUNCTION create_reservation(jsonb,jsonb),take_rate_limit(text,int),replace_channel_blocks(text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION create_reservation(jsonb,jsonb),take_rate_limit(text,int),replace_channel_blocks(text,jsonb) TO service_role;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE users FROM anon, authenticated;
GRANT ALL ON TABLE users TO service_role;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE rooms FROM anon, authenticated;
GRANT ALL ON TABLE rooms TO service_role;
ALTER TABLE room_images ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE room_images FROM anon, authenticated;
GRANT ALL ON TABLE room_images TO service_role;
ALTER TABLE amenities ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE amenities FROM anon, authenticated;
GRANT ALL ON TABLE amenities TO service_role;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE bookings FROM anon, authenticated;
GRANT ALL ON TABLE bookings TO service_role;
ALTER TABLE booking_guests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE booking_guests FROM anon, authenticated;
GRANT ALL ON TABLE booking_guests TO service_role;
ALTER TABLE booking_sources ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE booking_sources FROM anon, authenticated;
GRANT ALL ON TABLE booking_sources TO service_role;
ALTER TABLE availability_blocks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE availability_blocks FROM anon, authenticated;
GRANT ALL ON TABLE availability_blocks TO service_role;
ALTER TABLE functions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE functions FROM anon, authenticated;
GRANT ALL ON TABLE functions TO service_role;
ALTER TABLE function_enquiries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE function_enquiries FROM anon, authenticated;
GRANT ALL ON TABLE function_enquiries TO service_role;
ALTER TABLE guests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE guests FROM anon, authenticated;
GRANT ALL ON TABLE guests TO service_role;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE blog_posts FROM anon, authenticated;
GRANT ALL ON TABLE blog_posts TO service_role;
ALTER TABLE blog_categories ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE blog_categories FROM anon, authenticated;
GRANT ALL ON TABLE blog_categories TO service_role;
ALTER TABLE gallery_images ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE gallery_images FROM anon, authenticated;
GRANT ALL ON TABLE gallery_images TO service_role;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE testimonials FROM anon, authenticated;
GRANT ALL ON TABLE testimonials TO service_role;
ALTER TABLE faqs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE faqs FROM anon, authenticated;
GRANT ALL ON TABLE faqs TO service_role;
ALTER TABLE website_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE website_settings FROM anon, authenticated;
GRANT ALL ON TABLE website_settings TO service_role;
ALTER TABLE seo_metadata ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE seo_metadata FROM anon, authenticated;
GRANT ALL ON TABLE seo_metadata TO service_role;
ALTER TABLE integration_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE integration_settings FROM anon, authenticated;
GRANT ALL ON TABLE integration_settings TO service_role;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE audit_logs FROM anon, authenticated;
GRANT ALL ON TABLE audit_logs TO service_role;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE sessions FROM anon, authenticated;
GRANT ALL ON TABLE sessions TO service_role;
ALTER TABLE reset_tokens ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE reset_tokens FROM anon, authenticated;
GRANT ALL ON TABLE reset_tokens TO service_role;
ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE rate_limits FROM anon, authenticated;
GRANT ALL ON TABLE rate_limits TO service_role;
ALTER TABLE email_outbox ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE email_outbox FROM anon, authenticated;
GRANT ALL ON TABLE email_outbox TO service_role;
ALTER TABLE contact_enquiries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE contact_enquiries FROM anon, authenticated;
GRANT ALL ON TABLE contact_enquiries TO service_role;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE menu_items FROM anon, authenticated;
GRANT ALL ON TABLE menu_items TO service_role;
ALTER TABLE availability_blocks ADD COLUMN function_id TEXT REFERENCES functions(id);
CREATE INDEX block_function ON availability_blocks(function_id);
CREATE OR REPLACE FUNCTION save_function(function_record jsonb,room_ids text[]) RETURNS jsonb LANGUAGE plpgsql AS $$ DECLARE t text:=now()::text; r text; BEGIN
 DELETE FROM availability_blocks WHERE function_id=function_record->>'id';
 INSERT INTO functions(id,checkin,checkout,status,data,created_at,updated_at) VALUES(function_record->>'id',function_record->>'checkin',function_record->>'checkout',function_record->>'status',function_record,t,t) ON CONFLICT(id) DO UPDATE SET checkin=excluded.checkin,checkout=excluded.checkout,status=excluded.status,data=excluded.data,updated_at=excluded.updated_at;
 IF function_record->>'status'='CONFIRMED' THEN FOREACH r IN ARRAY room_ids LOOP
 INSERT INTO availability_blocks(id,room_id,checkin,checkout,source,function_id,data,created_at,updated_at) VALUES(gen_random_uuid()::text,r,function_record->>'checkin',function_record->>'checkout','FUNCTION',function_record->>'id',jsonb_build_object('notes',function_record->>'name'),t,t);
 END LOOP; END IF;
 INSERT INTO audit_logs(id,data,created_at,updated_at) VALUES(gen_random_uuid()::text,jsonb_build_object('action','function.saved','function_id',function_record->>'id'),t,t);
 RETURN function_record; END $$;
REVOKE ALL ON FUNCTION save_function(jsonb,text[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION save_function(jsonb,text[]) TO service_role;
