export type FormField = {
  key: string;
  label: string;
  type?: string;
  options?: string[];
  required?: boolean;
};
export const schemas: Record<string, FormField[]> = {
  seo_metadata: [
    {
      key: "id",
      label: "Page path (for example /accommodation)",
      required: true,
    },
    { key: "title", label: "SEO title", required: true },
    {
      key: "description",
      label: "Meta description",
      type: "textarea",
      required: true,
    },
  ],
  rooms: [
    { key: "name", label: "Room name", required: true },
    { key: "description", label: "Description", type: "textarea" },
    { key: "image", label: "Main photograph", type: "image" },
    { key: "capacity", label: "Maximum guests", type: "number" },
    { key: "beds", label: "Bed configuration" },
    { key: "bathroom", label: "Bathroom details" },
    { key: "amenities", label: "Amenities (one per line)", type: "textarea" },
    { key: "price", label: "Nightly price in ZAR", type: "number" },
    { key: "featured", label: "Featured room", type: "boolean" },
    { key: "published", label: "Published on website", type: "boolean" },
  ],
  bookings: [
    { key: "room_id", label: "Room", type: "room" },
    { key: "checkin", label: "Check-in", type: "date", required: true },
    { key: "checkout", label: "Check-out", type: "date", required: true },
    { key: "first_name", label: "First name", required: true },
    { key: "last_name", label: "Last name", required: true },
    { key: "email", label: "Email", type: "email", required: true },
    { key: "phone", label: "Phone", required: true },
    { key: "adults", label: "Adults", type: "number" },
    { key: "children", label: "Children", type: "number" },
    { key: "arrival_time", label: "Expected arrival", type: "time" },
    {
      key: "source",
      label: "Booking source",
      options: ["ADMIN", "DIRECT", "LEKKESLAAP", "BOOKING.COM", "OTHER"],
    },
    {
      key: "status",
      label: "Booking status",
      options: [
        "ENQUIRY",
        "PENDING",
        "CONFIRMED",
        "PAID",
        "CHECKED-IN",
        "CHECKED-OUT",
        "CANCELLED",
        "NO-SHOW",
      ],
    },
    {
      key: "payment_status",
      label: "Payment status",
      options: ["UNPAID", "DEPOSIT PAID", "PAID", "REFUNDED"],
    },
    { key: "notes", label: "Notes / reason for change", type: "textarea" },
  ],
  availability_blocks: [
    { key: "room_id", label: "Room to block", type: "room" },
    { key: "checkin", label: "From date", type: "date", required: true },
    {
      key: "checkout",
      label: "Until date (exclusive)",
      type: "date",
      required: true,
    },
    {
      key: "notes",
      label: "Reason / function reference",
      type: "textarea",
      required: true,
    },
  ],
  functions: [
    {
      key: "affected_room_ids",
      label: "Rooms to block when confirmed",
      type: "rooms",
    },
    { key: "name", label: "Function name", required: true },
    { key: "email", label: "Contact email", type: "email" },
    { key: "phone", label: "Contact phone" },
    { key: "event_type", label: "Event type" },
    { key: "checkin", label: "Date", type: "date", required: true },
    {
      key: "checkout",
      label: "End date (next day for one-day events)",
      type: "date",
      required: true,
    },
    { key: "start_time", label: "Start time", type: "time" },
    { key: "end_time", label: "End time", type: "time" },
    { key: "guests", label: "Number of guests", type: "number" },
    { key: "catering", label: "Catering requirements", type: "textarea" },
    {
      key: "accommodation",
      label: "Accommodation requirements",
      type: "textarea",
    },
    {
      key: "status",
      label: "Status",
      options: [
        "NEW",
        "CONTACTED",
        "QUOTED",
        "CONFIRMED",
        "DECLINED",
        "COMPLETED",
      ],
    },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  function_enquiries: [
    { key: "name", label: "Name" },
    { key: "email", label: "Email", type: "email" },
    { key: "phone", label: "Phone" },
    { key: "event_type", label: "Event type" },
    { key: "preferred_date", label: "Preferred date", type: "date" },
    { key: "guests", label: "Guests", type: "number" },
    { key: "start_time", label: "Start", type: "time" },
    { key: "end_time", label: "End", type: "time" },
    { key: "catering", label: "Catering", type: "textarea" },
    { key: "accommodation", label: "Accommodation" },
    { key: "message", label: "Message", type: "textarea" },
    {
      key: "status",
      label: "Status",
      options: [
        "NEW",
        "CONTACTED",
        "QUOTED",
        "CONFIRMED",
        "DECLINED",
        "COMPLETED",
      ],
    },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  blog_posts: [
    { key: "title", label: "Article title", required: true },
    { key: "slug", label: "URL slug", required: true },
    { key: "description", label: "Short introduction", type: "textarea" },
    { key: "category", label: "Category" },
    { key: "image", label: "Featured image", type: "image" },
    { key: "alt", label: "Image alt text" },
    {
      key: "body",
      label: "Article (## headings, paragraphs and [links](/path))",
      type: "textarea",
    },
    { key: "author", label: "Author" },
    { key: "published_at", label: "Publish date", type: "date" },
    { key: "seo_title", label: "SEO title" },
    { key: "seo_description", label: "SEO description", type: "textarea" },
    { key: "published", label: "Published", type: "boolean" },
  ],
  gallery_images: [
    { key: "title", label: "Caption", required: true },
    { key: "image", label: "Photograph", type: "image" },
    { key: "alt", label: "Alt text", required: true },
    {
      key: "category",
      label: "Category",
      options: [
        "Property",
        "Rooms",
        "Food",
        "Garden",
        "Nature",
        "Pool",
        "Boma",
        "Farmhouse",
        "Local area",
      ],
    },
    { key: "sort_order", label: "Display order", type: "number" },
    { key: "published", label: "Published", type: "boolean" },
  ],
  faqs: [
    { key: "title", label: "Question", required: true },
    {
      key: "description",
      label: "Verified answer",
      type: "textarea",
      required: true,
    },
    { key: "sort_order", label: "Display order", type: "number" },
    { key: "published", label: "Published", type: "boolean" },
  ],
  testimonials: [
    { key: "guest_name", label: "Guest name", required: true },
    { key: "review", label: "Review text", type: "textarea", required: true },
    { key: "rating", label: "Rating (1–5)", type: "number" },
    { key: "source", label: "Source" },
    { key: "source_url", label: "Verification URL" },
    { key: "date", label: "Review date", type: "date" },
    {
      key: "verified",
      label: "I have verified this genuine review",
      type: "boolean",
    },
    { key: "published", label: "Published", type: "boolean" },
  ],
  integration_settings: [
    { key: "name", label: "Integration name", required: true },
    {
      key: "channel",
      label: "Channel",
      options: ["BOOKING.COM", "LEKKESLAAP", "OTHER"],
    },
    { key: "room_id", label: "Mapped room", type: "room" },
    { key: "external_unit_id", label: "Channel property / unit ID" },
    { key: "feed_env", label: "ICS URL environment variable name" },
    {
      key: "api_env",
      label: "API credentials environment variable name (future adapter)",
    },
    {
      key: "frequency_minutes",
      label: "Sync frequency (minutes, minimum 15)",
      type: "number",
    },
    { key: "enabled", label: "Enable calendar sync", type: "boolean" },
  ],
  menu_items: [
    { key: "name", label: "Item", required: true },
    { key: "category", label: "Category" },
    { key: "description", label: "Description", type: "textarea" },
    { key: "price", label: "Price (ZAR)", type: "number" },
    { key: "image", label: "Image", type: "image" },
    { key: "published", label: "Available on website", type: "boolean" },
  ],
  room_images: [
    { key: "room_id", label: "Room", type: "room" },
    { key: "title", label: "Caption" },
    { key: "image", label: "Image", type: "image" },
    { key: "alt", label: "Alt text" },
    { key: "sort_order", label: "Display order", type: "number" },
  ],
};
